export const filterList = [
    {
        name : "Comida típica",
        filter:"tipica",
        class : "filter-button",
        level : 1,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar comida típica",
        
    },
    {
        name : "Comida popular",
        filter:"popular",
        class : "filter-button",
        level : 1,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar comida popular",
    },
    {
        name : "Platillos principales",
        filter:"principales",
        class : "filter-button",
        level : 2,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar por platillos principales",
    },
    {
        name : "Bebidas",
        filter:"bebidas",
        class : "filter-button",
        level : 2,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar por bebidas",
    },
    {
        name : "Postres",
        filter:"postres",
        class : "filter-button",
        level : 2,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar por postres",
    },
    {
        name: "Favoritos de la comunidad",
        filter:"mejores",
        class : "filter-button",
        level : 0,
        image: "/img/carousel/platillos-principales.jpg",
        description: "10 recetas favoritas de la comunidad",
    },
    {
        name: "Todas las recetas",
        filter:"todas",
        class : "filter-button",
        level : 0,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Mostrar todas las recetas",
    },
    {
        name: "Mis favoritos",
        path:"/recipes/favorites",
        class : "filter-button",
        level : 0,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Ir a mis recetas favoritas",
    },

];
