export const filterList = [
    {
        name : "Comida típica",
        filter:"Comida típica",
        class : "filter-button",
        level : 1,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar comida típica",
        
    },
    {
        name : "Comida popular",
        filter:"Comida popular",
        class : "filter-button",
        level : 1,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar comida popular",
    },
    {
        name : "Platillos principales",
        filter:"Platillos principales",
        class : "filter-button",
        level : 2,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar por platillos principales",
    },
    {
        name : "Bebidas",
        filter:"Bebidas",
        class : "filter-button",
        level : 2,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar por bebidas",
    },
    {
        name : "Postres",
        filter:"Postres",
        class : "filter-button",
        level : 2,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar por postres",
    },
    {
        name: "Las 10 mejores calificaciones",
        filter:"Las 10 mejores calificaciones",
        class : "filter-button",
        level : 0,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Buscar las 10 mejores calificaciones",
    },
    {
        name: "Todas las recetas",
        filter:".",
        class : "filter-button",
        level : 0,
        image: "/img/carousel/platillos-principales.jpg",
        description: "Mostrar todas las recetas",
    },

]