export const initialState ={
    user : {
        id: "123",
        loginState: true,
        name : "Bellota Saltarina",
        email : "belloti@gmail.com",
        favorites : [2,3,7]
    },
    recipes:  [
        {   id:1,
            name: "Piquemacho",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 7,
            favorite: false,
            time: 2,
            difficulty : 10,
            recommended : true,
        },
        {
            id:2,
            name: "Huminta",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 9,
            favorite: false,
            time: 2,
            difficulty : 10,
            recommended : false,
        },
        {
            id:3,
            name: "Salteña",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 10,
            favorite: true,
            time: 2,
            difficulty : 10,
            recommended : true,
        },
        {
            id:4,
            name: "Salchipapa",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 10,
            favorite: true,
            time: 2,
            difficulty : 10,
            recommended : false,
        },
        {
            id:5,
            name: "Ají de fideo",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 5,
            favorite: true,
            time: 2,
            difficulty : 10,
            recommended : true,
        },
        {
            id:6,
            name: "Ají de papa",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 1,
            favorite: true,
            time: 2,
            difficulty : 10,
            recommended : true,
        },
        {
            id:7,
            name: "Hamburguesa de quinua",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 5,
            favorite: false,
            time: 2,
            difficulty : 8,
        },
        {
            id:8,
            name: "Plato paceño a la potosina",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 5,
            favorite: false,
            time: 2,
            difficulty : 10,
            recommended : false,
        },
        {
            id:9,
            name: "Ají de fideo",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 4,
            favorite: true,
            time: 2,
            difficulty : 10,
            recommended : true,
        },
        {
            id:10,
            name: "Hamburguesa de quinua",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 3,
            favorite: false,
            time: 2,
            difficulty : 10,
            recommended : true,
        },
        {
            id:11,
            name: "Api con pastel",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 10,
            favorite: false,
            time: 2,
            difficulty : 5,
        },
        {
            id:12,
            name: "Alfajor",
            image: "/img/carousel/platillos-principales.jpg",
            description: "Buscar comida típica",
            punctuation: 7,
            favorite: false,
            time: 2,
            difficulty : 10,
            recommended : true,
        },

    ],
};

/* const bestPunctuationList = initialState.recipes.sort((a,b) => {
    return b.punctuation - a.punctuation;
});
console.log(
    bestPunctuationList
)
 */

/* const recomendationList = [...initialState.recipes].filter(recipe => recipe.recommended === true);
console.log(recomendationList); */